# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository.
version: '3.9'

services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--serversTransport.maxIdleConnsPerHost=200"
      - "--serversTransport.forwardingTimeouts.dialTimeout=0"
      - "--serversTransport.forwardingTimeouts.responseHeaderTimeout=0"
      - "--serversTransport.forwardingTimeouts.idleConnTimeout=0"
    networks:
      - testcenter

  testcenter-db:
    build:
      context: ..
      dockerfile: docker/database.Dockerfile
    ports:
      - "9091:3306"
    command:
      - --log_error_verbosity=2
    volumes:
      - ../scripts/database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ../scripts/database/000-create-test-db.sh:/docker-entrypoint-initdb.d/000-create-test-db.sh
    healthcheck: # solved timing problems on the CI even though the backend uses ConnectWithRetries
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      retries: 120
    networks:
      - testcenter

  testcenter-backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      target: dev
    volumes:
      - ../backend/.htaccess:/var/www/backend/.htaccess
      - ../backend/config/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ../backend/index.php:/var/www/backend/index.php
      - ../backend/initialize.php:/var/www/backend/initialize.php
      - ../backend/routes.php:/var/www/backend/routes.php
      - ../backend/src:/var/www/backend/src
      - ../backend/test:/var/www/backend/test
      - ../data:/var/www/data
      - ../scripts/database:/var/www/scripts/database
      - ../definitions:/var/www/definitions
      - ../docs/dist:/docs/dist
      - ../package.json:/var/www/package.json
      - ../sampledata:/var/www/sampledata
      - ../backend/config/no-cors.htaccess/:/var/www/.htaccess
      - ../backend/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../backend/config/local.php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 9005:9003
    depends_on:
      testcenter-db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - testcenter

  testcenter-frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      target: dev
    volumes:
      - ../common:/common
      - ../definitions:/definitions
      - ../frontend/src:/app/src
#      - ./docs/dist:/docs/dist TODO don't we need this for karma test coverage?
    networks:
      - testcenter

  testcenter-broadcasting-service:
    build:
      context: ..
      dockerfile: docker/broadcasting-service.Dockerfile
      target: dev
    volumes:
      - ../common:/common
      - ../broadcasting-service/src:/app/src
    networks:
      - testcenter

  testcenter-file-service:
    build:
      context: ..
      dockerfile: docker/file-service.Dockerfile
      args:
        ENABLED_MODULES: lua
    volumes:
      - ../sampledata/sample_resource_package.itcr.zip:/var/www/data-TEST/ws_1/Resource/sample_resource_package.itcr.zip
      - ../sampledata/SAMPLE_UNITCONTENTS.HTM:/var/www/data-TEST/ws_1/Resource/SAMPLE_UNITCONTENTS.HTM
      - ../sampledata/verona-player-simple-4.0.0.html:/var/www/data-TEST/ws_1/Resource/verona-player-simple-4.0.0.html
      - ../data:/var/www/html/
      - ../scripts/file-service/nginx.conf:/etc/nginx/nginx.conf
      - ../scripts/file-service/auth/:/usr/share/nginx/auth
      - ../scripts/file-service/no-cors.conf:/etc/nginx/conf.d/cors.conf
    networks:
      - testcenter

  testcenter-cache-service:
    ports:
      - "6379:6379"

  testcenter-task-runner:
    container_name: testcenter-runner
    profiles:
      - task-runner
    build:
      context: ..
      dockerfile: docker/runner.Dockerfile
    volumes:
      - ../README.md:/app/README.md
      - ../broadcasting-service:/app/broadcasting-service
      - ../common:/app/common
      - ../definitions:/app/definitions
      - ../dist-src:/app/dist-src
      - ../dist:/app/dist
      - ../docker/docker-compose.yml:/app/docker-compose.yml
      - ../docs:/app/docs
      - ../frontend:/app/frontend
      - ../package.json:/app/package.json
      - ../sampledata:/app/sampledata
      - ../scripts:/app/scripts
      - ../test/api:/app/test/api
      - ../test/config.docker.json:/app/test/config.json
    networks:
      - testcenter